language: node_js
branches:
  only: 
    - master
node_js:
  - "0.12.7"
npm:
  - "2.11.3"
after_success:
  - bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "d49917e17229"
  - COMMIT_AUTHOR_EMAIL: "jy@binary.com"